name: Update Categoria1

on:
  schedule:
    - cron: '0 * * * *' # Ejecuta cada hora (puedes modificar el horario)
  workflow_dispatch:

permissions:
  contents: write # Permiso para permitir push al repositorio

jobs:
  updateCategoria1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch Tournament Data
        env:
          CHALLONGE_API_KEY: ${{ secrets.CHALLONGE_API_KEY }} # Token de API de Challonge
        run: |
          TOURNAMENT_ID="e4lvbpfj" # Reemplaza con el ID de tu torneo
          curl -s -G "https://api.challonge.com/v1/tournaments/$TOURNAMENT_ID.json" \
          -d "api_key=$CHALLONGE_API_KEY" \
          -d "include_participants=1" \
          -d "include_matches=1" \
          > categoria1.json

      - name: Commit and Push changes
        run: |
          git config --global user.email "alegenio2@gmail.com" # Usa tu email aquí
          git config --global user.name "Alegenio2" # Usa tu nombre de usuario aquí
          git add categoria1.json
          git commit -m "Update Categoria1"
          git push
