name: Fetch Age of Empires Feed

on:
  schedule:
    - cron: '0 */6 * * *' # Ejecuta cada 6 horas
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  fetch_feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Puedes elegir la versión que necesites

      - name: Install dependencies
        run: npm install

      - name: Fetch Age of Empires Feed
        run: |
          curl -s https://www.ageofempires.com/feed/ -o feed.xml
          node fetch-feed.js # Ejecuta el script que parsea el XML y lo guarda en JSON

      - name: Commit feed data
        run: |
          git config --global user.email "alegenio2@gmail.com"
          git config --global user.name "Alegenio2"
          git add feed.json
          git commit -m "Update feed data"
          git push
